"""
Evidence Module - Graph Engineering Evidence Management for mLoop.

Implements structured, typed evidence carrying between DAG nodes ("An Edge Should Carry Evidence").
Replaces raw text chatting between agents with structured, verifiable evidence items.
Includes DeterministicContractMirror to prevent Concurrency Drift and ensure contract isomorphism.
"""

import os
import json
import time
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple, Any
import logging

logger = logging.getLogger("evidence")

@dataclass
class EvidenceItem:
    """Represents a single atomic piece of evidence generated by a DAG node."""
    evidence_id: str
    target_file: str
    line_range: Tuple[int, int]
    rule_ref: str           # e.g., 'RM-001', 'GHERKIN_4_PILLARS', 'INVEST_SCORE', 'API_ROUTE'
    confidence: float       # 0.0 to 1.0
    risk_level: str         # 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL'
    description: str
    evidence_payload: Dict[str, Any] = field(default_factory=dict)
    timestamp: float = field(default_factory=time.time)

    def to_dict(self) -> Dict[str, Any]:
        """Convert evidence item to a serializable dictionary."""
        return {
            "evidence_id": self.evidence_id,
            "target_file": self.target_file,
            "line_range": list(self.line_range),
            "rule_ref": self.rule_ref,
            "confidence": self.confidence,
            "risk_level": self.risk_level,
            "description": self.description,
            "evidence_payload": self.evidence_payload,
            "timestamp": self.timestamp,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "EvidenceItem":
        """Create an EvidenceItem instance from a dictionary."""
        line_range = tuple(data.get("line_range", [0, 0]))
        return cls(
            evidence_id=data.get("evidence_id", ""),
            target_file=data.get("target_file", ""),
            line_range=(line_range[0], line_range[1]),
            rule_ref=data.get("rule_ref", "GENERAL"),
            confidence=data.get("confidence", 1.0),
            risk_level=data.get("risk_level", "LOW"),
            description=data.get("description", ""),
            evidence_payload=data.get("evidence_payload", {}),
            timestamp=data.get("timestamp", time.time()),
        )

@dataclass
class EvidencePack:
    """Collection of evidence items passed along an edge in the DAG."""
    source_node: str
    initiative_name: str
    items: List[EvidenceItem] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)
    created_at: float = field(default_factory=time.time)

    def add_item(self, item: EvidenceItem) -> None:
        """Add an evidence item to the pack."""
        self.items.append(item)

    def get_highest_risk(self) -> str:
        """Determine highest risk level in the evidence pack."""
        risk_priority = {"CRITICAL": 4, "HIGH": 3, "MEDIUM": 2, "LOW": 1}
        max_priority = 1
        highest_risk = "LOW"

        for item in self.items:
            priority = risk_priority.get(item.risk_level.upper(), 1)
            if priority > max_priority:
                max_priority = priority
                highest_risk = item.risk_level.upper()

        return highest_risk

    def to_dict(self) -> Dict[str, Any]:
        """Convert evidence pack to a JSON-serializable dictionary."""
        return {
            "source_node": self.source_node,
            "initiative_name": self.initiative_name,
            "highest_risk": self.get_highest_risk(),
            "total_items": len(self.items),
            "items": [item.to_dict() for item in self.items],
            "metadata": self.metadata,
            "created_at": self.created_at,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "EvidencePack":
        """Reconstruct EvidencePack from dictionary."""
        items = [EvidenceItem.from_dict(item_data) for item_data in data.get("items", [])]
        return cls(
            source_node=data.get("source_node", "unknown"),
            initiative_name=data.get("initiative_name", "default"),
            items=items,
            metadata=data.get("metadata", {}),
            created_at=data.get("created_at", time.time()),
        )


class DeterministicContractMirror:
    """
    Deterministic AST & contract symmetry checker (Blindspot #6 - Concurrency Drift).
    Cross-checks endpoints, routes, methods, and payload structures declared across
    parallel evidence items before merging, with 0ms LLM overhead.
    """
    @staticmethod
    def verify_contract_symmetry(packs: List[EvidencePack]) -> Tuple[bool, List[str]]:
        """
        Validates that API routes, models, or schema definitions declared in parallel packs
        are consistent and do not contradict each other.
        """
        violations: List[str] = []
        route_declarations: Dict[str, Dict[str, Any]] = {}

        for pack in packs:
            for item in pack.items:
                payload = item.evidence_payload
                if not payload:
                    continue
                
                # Check API route definitions
                route = payload.get("route") or payload.get("api_route")
                if route:
                    method = (payload.get("method") or "GET").upper()
                    key = f"{method} {route}"
                    existing = route_declarations.get(key)
                    if existing:
                        # Compare declared fields / params if present
                        fields1 = set(payload.get("fields", []))
                        fields2 = set(existing.get("fields", []))
                        if fields1 and fields2 and fields1 != fields2:
                            diff = fields1.symmetric_difference(fields2)
                            violations.append(
                                f"Contract Drift on '{key}': declared by '{pack.source_node}' with diff {diff} vs '{existing.get('source_node')}'"
                            )
                    else:
                        route_declarations[key] = {
                            "source_node": pack.source_node,
                            "fields": payload.get("fields", []),
                            "description": item.description
                        }

        is_symmetric = len(violations) == 0
        return is_symmetric, violations


class EvidenceReducer:
    """
    Deterministic code node for merging, deduplicating, compressing,
    and verifying contract symmetry across evidence packs from parallel Fan-Out nodes.
    """

    @staticmethod
    def merge_and_deduplicate(packs: List[EvidencePack], target_node_name: str) -> EvidencePack:
        """
        Merges multiple EvidencePacks, deduplicating items based on (target_file, rule_ref, description).
        Verifies contract symmetry across packs and annotates metadata.
        Returns a compressed, unified EvidencePack.
        """
        merged_items: List[EvidenceItem] = []
        seen_keys = set()
        initiative_name = packs[0].initiative_name if packs else "default"

        # Check contract symmetry
        is_symmetric, contract_violations = DeterministicContractMirror.verify_contract_symmetry(packs)
        if not is_symmetric:
            for viol in contract_violations:
                logger.warning(f"[EvidenceReducer] {viol}")

        for pack in packs:
            for item in pack.items:
                dedup_key = (item.target_file, item.rule_ref, item.description.strip().lower())
                if dedup_key not in seen_keys:
                    seen_keys.add(dedup_key)
                    merged_items.append(item)
                else:
                    logger.debug(f"[EvidenceReducer] Duplicate item skipped: {dedup_key}")

        merged_pack = EvidencePack(
            source_node=target_node_name,
            initiative_name=initiative_name,
            items=merged_items,
            metadata={
                "merged_packs_count": len(packs),
                "original_total_items": sum(len(p.items) for p in packs),
                "deduplicated_items_count": len(merged_items),
                "contract_symmetry": is_symmetric,
                "contract_violations": contract_violations,
            }
        )
        return merged_pack
