"""
Structures de données et métadonnées pour le Guide CLI SSOT (ADR-0370).
Extraction modulaire pour conformité ADR-0202 (≤ 300L).
"""

from typing import Dict

PHASE_MAPPING: Dict[str, str] = {
    # Phase 0 : INCEPTION (Gathering, Cadrage & SOW)
    "init": "sow",
    "to-sow": "sow",
    "ingest": "sow",
    "research": "sow",
    # Phase 1 : SPEC / INGEST (Ingestion & Analyse Documentaire)
    "crawl": "spec",
    "extract": "spec",
    "agentic-extract": "spec",
    "chunk": "spec",
    "parent-resolve": "spec",
    "deep-search": "spec",
    "csv-normalize": "spec",
    "csv-validate": "spec",
    "code-init": "spec",
    "code-status": "spec",
    "jira-read": "spec",
    # Phase 2 : PLAN / ARCHI (Planification, Architecture, Grill & Découpage)
    "focus": "plan",
    "grill": "plan",
    "grill-project": "plan",
    "to-tshirt": "plan",
    "to-spec": "plan",
    "to-tickets": "plan",
    "wayfinder": "plan",
    "drill": "plan",
    "deepen": "plan",
    "goal-cascade": "plan",
    "distill-invest": "plan",
    "graph-query": "plan",
    "graph-explain": "plan",
    "graph-impact": "plan",
    "graph-status": "plan",
    "hyper-query": "plan",
    "archify": "plan",
    "drawdb": "plan",
    "canvas": "plan",
    "export-obsidian": "plan",
    "story-clean": "plan",
    "update-story": "plan",
    "dossier-init": "plan",
    "multi-draft": "plan",
    # Phase 3 : BUILD / DEV (Développement & Workers Multi-Agents)
    "self-dev": "build",
    "confidence": "build",
    "worker-spawn": "build",
    "worker-status": "build",
    "worker-close": "build",
    "worker-harvest": "build",
    "worker-reap": "build",
    "worker-handoff-test": "build",
    "worker-legacy-mine": "build",
    "worker-shadow-estimate": "build",
    "worker-visual-dissect": "build",
    "worker-janitor-watch": "build",
    "code-explore": "build",
    "code-impact": "build",
    "code-affected": "build",
    "csv-diff": "build",
    "csv-anonymize": "build",
    "review": "build",
    "annotate": "build",
    "code-check": "build",
    "code-tournament": "build",
    "tdd-enforce": "build",
    "opencode": "build",
    "plannotator": "build",
    # Phase 4 : VALIDATE / QA (Validation Sémantique, Fact-Check & Guardrails)
    "validate-sprint": "validate",
    "wikifix": "validate",
    "struct-check": "validate",
    "rubber-duck": "validate",
    "audit-loop": "validate",
    "aoep": "validate",
    "fact-check": "validate",
    "fact-search": "validate",
    "check-leakage": "validate",
    "nli-audit": "validate",
    "gates": "validate",
    "gate-approve": "validate",
    "lifecycle-status": "validate",
    "lifecycle-clean": "validate",
    "tree": "validate",
    "guardian-status": "validate",
    "eval": "validate",
    "eval-harvest": "validate",
    "diagnose": "validate",
    "hill-climb": "validate",
    "skill-eval": "validate",
    # Phase 5 : SHIP & SYNC (Synchronisation, Jira Cloud & Distribution)
    "sync": "ship",
    "sync-antigravity": "ship",
    "rollover-archive": "ship",
    "jira_sync": "ship",
    "cycle-status": "ship",
    "calibrate": "ship",
    "plugin-validate": "ship",
    "plugin-export": "ship",
    "guide-export": "ship",
    "install-hooks": "ship",
    # Transverse / Observabilité, Mémoire, Tokens & Runtime
    "guide": "transverse",
    "completion-setup": "transverse",
    "resume": "transverse",
    "vibe-check": "transverse",
    "dashboard": "transverse",
    "app-server": "transverse",
    "mcp-serve": "transverse",
    "token-tracker": "transverse",
    "context-watch": "transverse",
    "cache-stats": "transverse",
    "cache-clear": "transverse",
    "memory-hygiene": "transverse",
    "supersession-sync": "transverse",
    "memo-search": "transverse",
    "blast": "transverse",
    "dream": "transverse",
    "unlearn": "transverse",
    "svg-optimize": "transverse",
    "teach": "transverse",
    "hook": "transverse",
    "doctor": "transverse",
    "agent-probe": "transverse",
    "skill-doctor": "transverse",
    "skill-list": "transverse",
    "skill-invoke": "transverse",
    "role-list": "transverse",
    "graph-run": "transverse",
    "optimize": "transverse",
    "agent-resilience": "transverse",
    "topology": "plan",
    "rollback": "transverse",
    "dream-rsi": "transverse",
    "memory": "transverse",
    "logs": "transverse",
    "crawler": "transverse",
    "scratch": "transverse",
}

PHASE_HEADERS: Dict[str, Dict[str, str]] = {
    "sow": {
        "title": "🟡 Phase 0 : INCEPTION (Gathering, Cadrage & SOW)",
        "desc": "Cadrage amont, ingestion initiale des briefs clients et génération de l'Énoncé des Travaux (SOW).",
    },
    "spec": {
        "title": "🟠 Phase 1 : SPEC / INGEST (Ingestion, Exploration & Données)",
        "desc": "Ingestion multimodale, Web Crawling, parsing de code source AST, conversion MarkItDown et normalisation tabulaire CSV.",
    },
    "plan": {
        "title": "🔵 Phase 2 : PLAN / ARCHI (Planification, Architecture, Grill & Découpage)",
        "desc": "Entrevues interactives Grill-with-Docs, découpage vertical INVEST, modélisation de données (DrawDB/Mermaid), hypergraphe et toiles Obsidian Canvas.",
    },
    "build": {
        "title": "🟢 Phase 3 : BUILD / DEV (Développement & Workers Multi-Agents)",
        "desc": "Orchestration multi-agents isolée (Herdr Fork & Harvest), revue de code visuelle Plannotator, exploration d'impact AST et auto-évolution.",
    },
    "validate": {
        "title": "🟣 Phase 4 : VALIDATE / QA (Validation Sémantique, Fact-Check & Guardrails)",
        "desc": "Audit de non-régression INVEST (WikiFix), Gatekeeper structurel (struct-check), audit contradictoire Sentinel (rubber-duck), Fact-Check NLI et Runnable Gates.",
    },
    "ship": {
        "title": "🔴 Phase 5 : SHIP & SYNC (Synchronisation, Jira Cloud & Distribution)",
        "desc": "Synchronisation bidirectionnelle Jira Cloud, synchronisation sémantique locale, publication Git, et packaging Agent Plugins 1.0.",
    },
    "transverse": {
        "title": "⚙️ Commandes Transverses (Observabilité, Mémoire, Tokens, Skills & Runtime)",
        "desc": "Surveillance de la fenêtre de contexte, audit des coûts TokenLedger, diagnostic des compétences (Skill Doctor), cache sémantique et serveurs d'API.",
    },
}

ARTEFACTS_MAP: Dict[str, str] = {
    "to-tshirt": "`docs/01-architecture/TSHIRT_SIZE_<PROJET>.md`",
    "to-sow": "`docs/01-architecture/SOW_<PROJET>.md`",
    "ingest": "`docs/00-ingested/` normalisé",
    "crawl": "`memory/crawler/cache/` (Markdown Twin)",
    "extract": "`docs/02-business-rules/`, `docs/03-models/`",
    "agentic-extract": "`docs/02-business-rules/RM-*.md`",
    "code-init": "Base SQLite `.codegraph/`",
    "focus": "Chargement de `backlog/stories/<ID>.md`",
    "grill": "ADRs dans `standards/adr-system/` & preuves",
    "grill-project": "`standards/adr-system/` & cadrage macro",
    "to-spec": "`docs/01-architecture/`",
    "to-tickets": "`backlog/stories/` + `sprint_backlog.md`",
    "archify": "Artefact HTML vectoriel interactif",
    "drawdb": "Interface DrawDB locale",
    "canvas": "`docs/05-assets/*.canvas`",
    "export-obsidian": "Coffre Obsidian structuré",
    "self-dev": "Code source sous `src/`",
    "worker-spawn": "Terminal PTY Herdr multiplexé",
    "worker-harvest": "Livrables intégrés sur disque",
    "wikifix": "`memory/wikifix_report.md`",
    "struct-check": "Rapport violations C1–C7",
    "rubber-duck": "Rapport sémantique 4 Piliers",
    "fact-check": "Certificat de véracité NLI",
    "sync": "Index FTS5 + Graphe sémantique",
    "jira_sync": "Tickets et champs Jira Cloud à jour",
    "plugin-export": "Package AP 1.0 redistribuable",
    "guide-export": "Guide HTML autonome Plannotator",
    "dossier-init": "`memory/evidence/<STORY_ID>_fact_dossier.md`",
    "gate-approve": "`memory/lifecycle_state.json` (Porte validée)",
    "lifecycle-status": "Console / Historique du cycle de vie",
    "completion-setup": "Ligne d'activation shell + emplacement `$PROFILE`",
    "lifecycle-clean": "Nettoyage stories orphelines",
    "agent-resilience": "Score & Audit de Cyber-Résilience (ADR-0371)",
    "topology": "Cartographie Blast Radius & Surface d'Exposition",
    "rollback": "Restauration PITR de l'état et mémoire saine",
    "dream-rsi": "Méta-Politique Optimale (.mloop/dream_policy.json)",
    "multi-draft": "Rapport Challenge Multi-Drafts (ADR-0373)",
    "code-check": "Rapport d'audit AST / Console",
    "code-tournament": "Matrice d'arbitrage Pareto ($S_{\\text{pareto}}$) & Code optimal",
    "tdd-enforce": "Sceau cryptographique TDD (Red / Green / Verify)",
    "validate-sprint": "Rapports d'assurance qualité QA (`qa_certification_report.md` et `.json`)",
    "opencode": "Configuration `.opencode/opencode.json` & runtime local",
    "plannotator": "Plan annoté dans `memory/plan/<STORY_ID>_phase_plan.annotated.md`",
    "memory": "Rapport de santé & défragmentation (`loop_mem.db` compacté)",
    "skill-eval": "Rapport d'évaluation des compétences (`skills_eval_summary.md`)",
    "rollover-archive": "Archive historique dans `backlog/archive/`",
}
